// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzlbkwoflkbrxfwqufyo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16bGJrd29mbGticnhmd3F1ZnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NDUzNDAsImV4cCI6MjA2NjAyMTM0MH0.Mgf3xH8d8-oCVkcHgH9gZMKH-dOmU74nGMvIaaS7Q10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);